import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Menu from "./components/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen mx-0 px-0">
          <Navbar />
          <div className="flex flex-col md:flex-row">
            <div className="w-full md:w-1/4 lg:w-1/6 p-4 bg-gray-600 text-white">
              <Menu />
            </div>
            <div className="flex-1 p-4 py-0">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
